sudo: required

language: generic

services:
  - docker
  
before_install:
  - docker build -t app .
  - docker run -d -p 8787:8787 app
  - docker ps -a
  - docker run app Rscript -e "install.packages('rsconnect')"
  - docker run app Rscript -e "rsconnect::setAccountInfo(name='adamrobinson361', token=Sys.getenv('Token'), secret=Sys.getenv('Secret'))"
  - docker run app Rscript -e "rsconnect::deployApp()"

