sudo: required

language: generic

services:
  - docker
  
before_install:
  - docker build -t app .
  - docker run -d -p 8787:8787 -e TRAVIS_SECRET -e TRAVIS_TOKEN --name "deployment_container" app 
  - docker ps -a
  - docker exec -it deployment_container Rscript -e "install.packages('rsconnect')"
  - docker exec -it deployment_container Rscript -e "rsconnect::setAccountInfo(name='adamrobinson361', token=Sys.getenv('TRAVIS_TOKEN'), secret=Sys.getenv('TRAVIS_SECRET'))"
  - docker exec -it deployment_container Rscript -e "rsconnect::deployApp(appDir = /home/rstudio/project/', appName = 'test')"
