sudo: required

language: generic

services:
  - docker
  
before_install:
  - docker build -t app .
  - docker run -d -p 8787:8787 -e TRAVIS_SECRET -e TRAVIS_TOKEN app
  - docker ps -a
  - docker run app Rscript -e "install.packages('rsconnect')"
  - docker run app Rscript -e "rsconnect::setAccountInfo(name='adamrobinson361', token=Sys.getenv('TRAVIS_TOKEN'), secret=Sys.getenv('TRAVIS_SECRET'))"
  - docker run app Rscript -e "rsconnect::deployApp()"

